services:
  api:
    build:
      context: .
      target: development
    command: npm run start:dev
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.10.0.10

  postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-dev}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-dev}
      POSTGRES_DB: ${DATABASE_NAME:-receipt_dev}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-dev} -d ${DATABASE_NAME:-receipt_dev}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      backend:
        ipv4_address: 10.10.0.11

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

volumes:
  pgdata:
